-- MySQL Script generated by MySQL Workbench
-- Thu Jan 27 22:51:43 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema avengers
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema avengers
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `avengers` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `avengers` ;

-- -----------------------------------------------------
-- Table `avengers`.`characters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avengers`.`characters` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `shortname` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avengers`.`writers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avengers`.`writers` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avengers`.`editors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avengers`.`editors` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avengers`.`colorists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avengers`.`colorists` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avengers`.`characters_has_editors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avengers`.`characters_has_editors` (
  `char_ID` INT UNSIGNED NOT NULL,
  `edit_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`char_ID`, `edit_ID`),
  INDEX `fk_characters_has_editors_editors1_idx` (`edit_ID` ASC),
  INDEX `fk_characters_has_editors_characters_idx` (`char_ID` ASC),
  CONSTRAINT `fk_characters_has_editors_characters`
    FOREIGN KEY (`char_ID`)
    REFERENCES `avengers`.`characters` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_characters_has_editors_editors1`
    FOREIGN KEY (`edit_ID`)
    REFERENCES `avengers`.`editors` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avengers`.`characters_has_writers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avengers`.`characters_has_writers` (
  `char_ID` INT UNSIGNED NOT NULL,
  `writer_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`char_ID`, `writer_ID`),
  INDEX `fk_characters_has_writers_writers1_idx` (`writer_ID` ASC),
  INDEX `fk_characters_has_writers_characters1_idx` (`char_ID` ASC),
  CONSTRAINT `fk_characters_has_writers_characters1`
    FOREIGN KEY (`char_ID`)
    REFERENCES `avengers`.`characters` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_characters_has_writers_writers1`
    FOREIGN KEY (`writer_ID`)
    REFERENCES `avengers`.`writers` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avengers`.`characters_has_colorists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avengers`.`characters_has_colorists` (
  `char_ID` INT UNSIGNED NOT NULL,
  `color_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`char_ID`, `color_ID`),
  INDEX `fk_characters_has_colorists_colorists1_idx` (`color_ID` ASC),
  INDEX `fk_characters_has_colorists_characters1_idx` (`char_ID` ASC),
  CONSTRAINT `fk_characters_has_colorists_characters1`
    FOREIGN KEY (`char_ID`)
    REFERENCES `avengers`.`characters` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_characters_has_colorists_colorists1`
    FOREIGN KEY (`color_ID`)
    REFERENCES `avengers`.`colorists` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `avengers`.`sync`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `avengers`.`sync` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `last_sync` DATETIME NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
